AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - db/schema.rb

################################################################################

Metrics/AbcSize:
  Max: 30

Metrics/LineLength:
  Max: 120
  Exclude:
    - spec/**/*

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*
    - config/environments/*
    - config/routes.rb

Metrics/ParameterLists:
  Max: 10

Metrics/CyclomaticComplexity:
  Max: 10

################################################################################

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/MixinUsage:
  Enabled: true
  Exclude:
    - bin/*
    - spec/**/*

################################################################################

Lint/AmbiguousBlockAssociation:
  Enabled: true
  Exclude:
    - spec/**/*

################################################################################

Naming/HeredocDelimiterNaming:
  Enabled: false
